// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6Qrq5wFU6tR1tl-AUxC8BvxPEaPrYqK4',
    appId: '1:380731474063:web:9d603b8c9da19f37fa70fa',
    messagingSenderId: '380731474063',
    projectId: 'tiktok-clone-22e50',
    authDomain: 'tiktok-clone-22e50.firebaseapp.com',
    storageBucket: 'tiktok-clone-22e50.appspot.com',
    measurementId: 'G-LD3596HCS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwtdIhiSttRYatDjIjhisCxNK1lKTVvg4',
    appId: '1:380731474063:android:9694fa08c84405fffa70fa',
    messagingSenderId: '380731474063',
    projectId: 'tiktok-clone-22e50',
    storageBucket: 'tiktok-clone-22e50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA964C2XII4ouUo0-HsRkAbWsfy4GaTsHI',
    appId: '1:380731474063:ios:bed9219a599a6b14fa70fa',
    messagingSenderId: '380731474063',
    projectId: 'tiktok-clone-22e50',
    storageBucket: 'tiktok-clone-22e50.appspot.com',
    iosClientId: '380731474063-n12oj35j8a28md4rsppt4mt1rs5je8u7.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA964C2XII4ouUo0-HsRkAbWsfy4GaTsHI',
    appId: '1:380731474063:ios:bed9219a599a6b14fa70fa',
    messagingSenderId: '380731474063',
    projectId: 'tiktok-clone-22e50',
    storageBucket: 'tiktok-clone-22e50.appspot.com',
    iosClientId: '380731474063-n12oj35j8a28md4rsppt4mt1rs5je8u7.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
